version: '3'

services:
    server:
      image: nginx
      container_name: nginx_srv
      volumes:
        - ./NGINX/nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - backend-service
        - mongodb
      ports:
       - 80:80
      #restart: on-failure
      networks:
       - traffic_net

    mongodb:
        image: mongo
        container_name: mongodb
        ports:
          - 27017:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: euro2020
          MONGO_INITDB_ROOT_PASSWORD: mershab99
        volumes:
          - /data/pit-0:/data/db
          - /data/logs/mongodb:/logs
        #restart: on-failure
        networks:
          - traffic_net

    backend-service:
        image: mershab99/euro2020betting
        environment:
          - ADMIN_USERNAME=admin
          - ADMIN_PASSWORD=euro2020
          - MONGO_HOST=mongodb
          - MONGO_PORT=27017
          - MONGO_USERNAME=euro2020
          - MONGO_PASSWORD=mershab99
          - LOG_FOLDER=/logs
          - MONGO_DB=dev
          - PORT=8000
          - ROSTER_URL=https://soccer.nbcsports.com/2021/06/08/euro-2020-squads-full-list-details-confirmed/
        volumes:
            - ./service:/code
            - /data/logs/api:/logs
        depends_on:
            - mongodb
        ports:
          - 8000:8000
        networks:
        - traffic_net

networks:
  traffic_net:
    driver: bridge
